export const INITIAL_CLASSROOMS = [
  {
    id: "room-a021",
    roomNumber: "A021",
    name: "A division",
    floor: 0,
    building: "Main Building",
    capacity: 60,
    type: "lecture_hall",
    benchStructure: { rows: 10, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a110",
    roomNumber: "A110",
    name: "GOI Lab",
    floor: 1,
    building: "Main Building",
    capacity: 30,
    type: "lab",
    benchStructure: { rows: 5, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a105",
    roomNumber: "A105",
    name: "OOPS Lab",
    floor: 1,
    building: "Main Building",
    capacity: 30,
    type: "lab",
    benchStructure: { rows: 5, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a107",
    roomNumber: "A107",
    name: "Chem Lab",
    floor: 1,
    building: "Main Building",
    capacity: 30,
    type: "lab",
    benchStructure: { rows: 5, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-b001",
    roomNumber: "B001",
    name: "Electrical Lab",
    floor: 0,
    building: "Workshop Block",
    capacity: 30,
    type: "lab",
    benchStructure: { rows: 5, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a023",
    roomNumber: "A023",
    name: "B division",
    floor: 0,
    building: "Main Building",
    capacity: 60,
    type: "lecture_hall",
    benchStructure: { rows: 10, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a024",
    roomNumber: "A024",
    name: "DTI Lab",
    floor: 0,
    building: "Main Building",
    capacity: 30,
    type: "lab",
    benchStructure: { rows: 5, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a026",
    roomNumber: "A026",
    name: "C division",
    floor: 0,
    building: "Main Building",
    capacity: 60,
    type: "lecture_hall",
    benchStructure: { rows: 10, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a028",
    roomNumber: "A028",
    name: "OOPS Lab",
    floor: 0,
    building: "Main Building",
    capacity: 30,
    type: "lab",
    benchStructure: { rows: 5, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a212",
    roomNumber: "A212",
    name: "D division",
    floor: 2,
    building: "Main Building",
    capacity: 60,
    type: "lecture_hall",
    benchStructure: { rows: 10, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-b010",
    roomNumber: "B010",
    name: "Electrical Lab",
    floor: 1,
    building: "Workshop Block",
    capacity: 30,
    type: "lab",
    benchStructure: { rows: 5, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a211",
    roomNumber: "A211",
    name: "G division",
    floor: 2,
    building: "Main Building",
    capacity: 60,
    type: "lecture_hall",
    benchStructure: { rows: 10, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a112",
    roomNumber: "A112",
    name: "GuI Lab",
    floor: 1,
    building: "Main Building",
    capacity: 30,
    type: "lab",
    benchStructure: { rows: 5, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a213",
    roomNumber: "A213",
    name: "E division",
    floor: 2,
    building: "Main Building",
    capacity: 60,
    type: "lecture_hall",
    benchStructure: { rows: 10, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a005",
    roomNumber: "A005",
    name: "MPW",
    floor: 0,
    building: "Main Building",
    capacity: 30,
    type: "lab",
    benchStructure: { rows: 5, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a210",
    roomNumber: "A210",
    name: "F division",
    floor: 2,
    building: "Main Building",
    capacity: 60,
    type: "lecture_hall",
    benchStructure: { rows: 10, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-a006",
    roomNumber: "A006",
    name: "MPW",
    floor: 0,
    building: "Main Building",
    capacity: 30,
    type: "lab",
    benchStructure: { rows: 5, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-b003",
    roomNumber: "B003",
    name: "Physics Lab",
    floor: 0,
    building: "Science Block",
    capacity: 30,
    type: "lab",
    benchStructure: { rows: 5, cols: 3, seatsPerBench: 2 },
  },
  {
    id: "room-b004",
    roomNumber: "B004",
    name: "MR Lab",
    floor: 0,
    building: "Science Block",
    capacity: 30,
    type: "lab",
    benchStructure: { rows: 5, cols: 3, seatsPerBench: 2 },
  },
];

export const INITIAL_FACULTY = [
  { abbr: "SNM", name: "DR. S. N. MALI" },
  { abbr: "AA", name: "DR. ALPANA ADSUL" },
  { abbr: "YDN", name: "Mr. YOGESH NAGVEKAR" },
  { abbr: "SSP", name: "Mr. SANDESH PATIL" },
  { abbr: "SMG", name: "Mr. SHUBHAM GADE" },
  { abbr: "RAP", name: "Mr. RAMCHANDRA POPALE" },
  { abbr: "SSM", name: "Mrs. SARITA MALI" },
  { abbr: "SRS", name: "Dr. SOPAN SHINDE" },
  { abbr: "SNE", name: "Mr. SURAJ ERBATNWAR" },
  { abbr: "PMR", name: "DR. POOJA RASTE" },
  { abbr: "SMK", name: "Mr. SHUBHAM KAVHAR" },
  { abbr: "AP", name: "Mr. ASHOK PATIL" },
  { abbr: "PAD", name: "DR. PURSHOOTAM DESAI" },
  { abbr: "MSA", name: "Mrs. MANISHA ASANE" },
  { abbr: "SBM", name: "Mrs. SAVITA MORE" },
  { abbr: "TBJ", name: "Ms. TANUJA JAYBHAYE" },
  { abbr: "SSJ", name: "Mr. SUJIT JALKOTE" },
  { abbr: "VS", name: "Dr. VARSHA SASE" },
  { abbr: "PNB", name: "Mrs. PRIYANKA BIKKAD" },
  { abbr: "MBS", name: "Miss MRUNALINI SHINDE" },
  { abbr: "PJK", name: "Miss. PRANALI KAMBLE" },
  { abbr: "RRJ", name: "Ms. RASIKA JADHAO" },
  { abbr: "AV", name: "Miss. AMISHA VASAIKAR" },
  { abbr: "SJ", name: "Mr. SIDDHI JADHAV" },
];

export const INITIAL_SUBJECTS = [
  "Advanced Engineering Calculus",
  "Modern Engineering Chemistry",
  "Modern Electrical Engineering",
  "Graphical User Interface",
  "Object Oriented Programming using C++",
  "Analog & Digital Electronics",
  "Modern Engineering Physics",
  "Mechanics for Robotics",
  "Design Thinking & Idea Lab",
  "Indian Knowledge System",
  "Manufacturing Practice Workshop",
  "Professional Communication Skills"
];

export const BRANCH_MAP: Record<string, string> = {
  "A": "Computer Engineering",
  "B": "Computer Engineering",
  "C": "Computer Engineering",
  "D": "AI & DS",
  "E": "AI & DS",
  "F": "AI & ML",
  "G": "AI & ML",
};

export const DIVISION_A_SCHEDULE: Record<string, any[]> = {
  "Monday": [
    { time: "09:15 - 10:15", subject: "AEC", teacher: "SMG", room: "A021", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "OOP", teacher: "MBS", room: "A021", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "AEC(T)", teacher: "SMG", room: "A021", type: "Tutorial", batch: "A1" },
    { time: "11:30 - 12:30", subject: "Library Hours", type: "Activity", batch: "A2/A3" },
    { time: "12:30 - 01:30", subject: "TG Contact Hour", type: "Activity" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 04:15", subject: "GUI(L)", teacher: "RRJ", room: "A110", type: "Lab", batch: "A1" },
    { time: "02:15 - 04:15", subject: "OOP(L)", teacher: "MBS", room: "A105", type: "Lab", batch: "A2" },
    { time: "02:15 - 04:15", subject: "DTI(L)", teacher: "AP", room: "A021", type: "Lab", batch: "A3" },
  ],
  "Tuesday": [
    { time: "09:15 - 10:15", subject: "MEC", teacher: "PAD", room: "A021", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "AEC", teacher: "SMG", room: "A021", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "AEC(T)", teacher: "SMG", room: "A021", type: "Tutorial", batch: "A2" },
    { time: "11:30 - 12:30", subject: "Library Hours", type: "Activity", batch: "A3/A1" },
    { time: "12:30 - 01:30", subject: "MEC", teacher: "PAD", room: "A021", type: "Lecture" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 04:15", subject: "MEC(L)", teacher: "PAD", room: "A107", type: "Lab", batch: "A1" },
    { time: "02:15 - 04:15", subject: "IKS(L)", teacher: "SNE", room: "A021", type: "Lab", batch: "A2" },
    { time: "02:15 - 04:15", subject: "MEE(L)", teacher: "SSJ", room: "B001", type: "Lab", batch: "A3" },
  ],
  "Wednesday": [
    { time: "09:15 - 10:15", subject: "MEE", teacher: "SSJ", room: "A021", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "Library Hours", type: "Activity" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "AEC(T)", teacher: "SMG", room: "A021", type: "Tutorial", batch: "A3" },
    { time: "11:30 - 12:30", subject: "Library Hours", type: "Activity", batch: "A1/A2" },
    { time: "12:30 - 01:30", subject: "AEC", teacher: "SMG", room: "A021", type: "Lecture" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 04:15", subject: "GUI(L)", teacher: "RRJ", room: "A110", type: "Lab", batch: "A2" },
    { time: "02:15 - 04:15", subject: "OOP(L)", teacher: "MBS", room: "A105", type: "Lab", batch: "A3" },
    { time: "02:15 - 04:15", subject: "DTI(L)", teacher: "TBJ", room: "A021", type: "Lab", batch: "A1" },
  ],
  "Thursday": [
    { time: "09:15 - 10:15", subject: "AEC", teacher: "SMG", room: "A021", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "MEE", teacher: "SSJ", room: "A021", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "MEC(L)", teacher: "PAD", room: "A107", type: "Lab", batch: "A3" },
    { time: "11:30 - 01:30", subject: "IKS(L)", teacher: "SMG", room: "A021", type: "Lab", batch: "A1" },
    { time: "11:30 - 01:30", subject: "MEE(L)", teacher: "SSJ", room: "B001", type: "Lab", batch: "A2" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 04:15", subject: "MEC(L)", teacher: "PAD", room: "A107", type: "Lab", batch: "A2" },
    { time: "02:15 - 04:15", subject: "IKS(L)", teacher: "SNE", room: "A021", type: "Lab", batch: "A3" },
    { time: "02:15 - 04:15", subject: "MEE(L)", teacher: "SSJ", room: "B001", type: "Lab", batch: "A1" },
  ],
  "Friday": [
    { time: "09:15 - 10:15", subject: "GUI", teacher: "SNM", room: "A021", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "GUI", teacher: "SNM", room: "A021", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "OOP", teacher: "MBS", room: "A021", type: "Lecture" },
    { time: "12:30 - 01:30", subject: "MEC", teacher: "PAD", room: "A021", type: "Lecture" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 04:15", subject: "GUI(L)", teacher: "RRJ", room: "A110", type: "Lab", batch: "A3" },
    { time: "02:15 - 04:15", subject: "OOP(L)", teacher: "MBS", room: "A105", type: "Lab", batch: "A1" },
    { time: "02:15 - 04:15", subject: "DTI(L)", teacher: "TBJ", room: "A024", type: "Lab", batch: "A2" },
  ],
  "Saturday": [
    { time: "09:15 - 10:15", subject: "CC Activity", type: "Activity" },
    { time: "10:15 - 11:15", subject: "Remedial Classes", type: "Activity" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "CC Activity", type: "Activity" },
    { time: "12:30 - 01:30", subject: "Remedial Classes", type: "Activity" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "CC Activity", type: "Activity" },
    { time: "03:15 - 04:15", subject: "Remedial Classes", type: "Activity" },
  ],
};

export const DIVISION_B_SCHEDULE: Record<string, any[]> = {
  "Monday": [
    { time: "09:15 - 10:15", subject: "MEE", teacher: "SSJ", room: "A023", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "MEC", teacher: "PAD", room: "A023", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "MEC(L)", teacher: "PAD", room: "A107", type: "Lab", batch: "B1" },
    { time: "11:30 - 01:30", subject: "IKS(L)", teacher: "SBM", room: "A023", type: "Lab", batch: "B2" },
    { time: "11:30 - 01:30", subject: "MEE(L)", teacher: "TBJ", room: "B001", type: "Lab", batch: "B3" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC", teacher: "SMG", room: "A023", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "AEC(T)", teacher: "SMG", room: "A023", type: "Tutorial", batch: "B1" },
    { time: "03:15 - 04:15", subject: "Library Hours", type: "Activity", batch: "B2/B3" },
  ],
  "Tuesday": [
    { time: "09:15 - 10:15", subject: "OOP", teacher: "MBS", room: "A023", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "MEE", teacher: "SSJ", room: "A023", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "GUI(L)", teacher: "RRJ", room: "A110", type: "Lab", batch: "B1" },
    { time: "11:30 - 01:30", subject: "OOP(L)", teacher: "MBS", room: "A105", type: "Lab", batch: "B2" },
    { time: "11:30 - 01:30", subject: "DTI(L)", teacher: "YDN", room: "A023", type: "Lab", batch: "B3" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC", teacher: "SMG", room: "A023", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "AEC(T)", teacher: "SMG", room: "A023", type: "Tutorial", batch: "B2" },
    { time: "03:15 - 04:15", subject: "Library Hours", type: "Activity", batch: "B3/B1" },
  ],
  "Wednesday": [
    { time: "09:15 - 11:15", subject: "GUI(L)", teacher: "RRJ", room: "A110", type: "Lab", batch: "B2" },
    { time: "09:15 - 11:15", subject: "OOP(L)", teacher: "MBS", room: "A105", type: "Lab", batch: "B3" },
    { time: "09:15 - 11:15", subject: "DTI(L)", teacher: "SNE", room: "A023", type: "Lab", batch: "B1" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "MEC(L)", teacher: "SNE", room: "A107", type: "Lab", batch: "B2" },
    { time: "11:30 - 01:30", subject: "Library Hours", type: "Activity", batch: "B3" },
    { time: "11:30 - 01:30", subject: "MEE(L)", teacher: "SMK", room: "B001", type: "Lab", batch: "B1" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC(T)", teacher: "SMG", room: "A023", type: "Tutorial", batch: "B3" },
    { time: "02:15 - 03:15", subject: "Library Hours", type: "Activity", batch: "B1/B2" },
    { time: "03:15 - 04:15", subject: "IKS", teacher: "SMG", room: "A023", type: "Lecture", batch: "B3" },
    { time: "03:15 - 04:15", subject: "Library Hours", type: "Activity", batch: "B1/B2" },
  ],
  "Thursday": [
    { time: "09:15 - 10:15", subject: "OOP", teacher: "MBS", room: "A023", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "MEC", teacher: "PAD", room: "A023", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "GUI(L)", teacher: "RRJ", room: "A110", type: "Lab", batch: "B3" },
    { time: "11:30 - 01:30", subject: "OOP(L)", teacher: "MBS", room: "A105", type: "Lab", batch: "B1" },
    { time: "11:30 - 01:30", subject: "DTI(L)", teacher: "YDN", room: "A023", type: "Lab", batch: "B2" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC", teacher: "SMG", room: "A023", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "TG Contact Hour", type: "Activity" },
  ],
  "Friday": [
    { time: "09:15 - 10:15", subject: "GUI", teacher: "AA", room: "A023", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "GUI", teacher: "AA", room: "A023", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "MEC(L)", teacher: "SNE", room: "A107", type: "Lab", batch: "B3" },
    { time: "11:30 - 01:30", subject: "IKS(L)", teacher: "SMG", room: "A023", type: "Lab", batch: "B1" },
    { time: "11:30 - 01:30", subject: "MEE(L)", teacher: "SMK", room: "B001", type: "Lab", batch: "B2" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC", teacher: "SMG", room: "A023", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "MEC", teacher: "PAD", room: "A023", type: "Lecture" },
  ],
  "Saturday": [
    { time: "09:15 - 10:15", subject: "CC Activity", type: "Activity" },
    { time: "10:15 - 11:15", subject: "Remedial Classes", type: "Activity" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "CC Activity", type: "Activity" },
    { time: "12:30 - 01:30", subject: "Remedial Classes", type: "Activity" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "CC Activity", type: "Activity" },
    { time: "03:15 - 04:15", subject: "Remedial Classes", type: "Activity" },
  ],
};

export const DIVISION_C_SCHEDULE: Record<string, any[]> = {
  "Monday": [
    { time: "09:15 - 11:15", subject: "MEC(L)", teacher: "MSA", room: "A107", type: "Lab", batch: "C1" },
    { time: "09:15 - 11:15", subject: "IKS(L)", teacher: "RAP", room: "A026", type: "Lab", batch: "C2" },
    { time: "09:15 - 11:15", subject: "MEE(L)", teacher: "VS", room: "B001", type: "Lab", batch: "C3" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "AEC", teacher: "RAP", room: "A026", type: "Lecture" },
    { time: "12:30 - 01:30", subject: "OOP", teacher: "PNB", room: "A026", type: "Lecture" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "MEC", teacher: "MSA", room: "A026", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "GUI", teacher: "AV", room: "A026", type: "Lecture" },
  ],
  "Tuesday": [
    { time: "09:15 - 11:15", subject: "GUI(L)", teacher: "AV", room: "A110", type: "Lab", batch: "C1" },
    { time: "09:15 - 11:15", subject: "OOP(L)", teacher: "PNB", room: "A028", type: "Lab", batch: "C2" },
    { time: "09:15 - 11:15", subject: "DTI(L)", teacher: "TBJ", room: "A026", type: "Lab", batch: "C3" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "MEE", teacher: "VS", room: "A026", type: "Lecture" },
    { time: "12:30 - 01:30", subject: "AEC", teacher: "RAP", room: "A026", type: "Lecture" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "OOP", teacher: "PNB", room: "A026", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "MEC", teacher: "MSA", room: "A026", type: "Lecture" },
  ],
  "Wednesday": [
    { time: "09:15 - 11:15", subject: "MEC(L)", teacher: "MSA", room: "A107", type: "Lab", batch: "C2" },
    { time: "09:15 - 11:15", subject: "IKS(L)", teacher: "RAP", room: "A026", type: "Lab", batch: "C3" },
    { time: "09:15 - 11:15", subject: "MEE(L)", teacher: "VS", room: "B001", type: "Lab", batch: "C1" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "AEC", teacher: "RAP", room: "A026", type: "Lecture" },
    { time: "12:30 - 01:30", subject: "MEE", teacher: "VS", room: "A026", type: "Lecture" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC(T)", teacher: "RAP", room: "A026", type: "Tutorial", batch: "C1" },
    { time: "02:15 - 03:15", subject: "Library Hours", type: "Activity", batch: "C2/C3" },
    { time: "03:15 - 04:15", subject: "MEC", teacher: "MSA", room: "A026", type: "Lecture" },
  ],
  "Thursday": [
    { time: "09:15 - 11:15", subject: "GUI(L)", teacher: "AV", room: "A110", type: "Lab", batch: "C2" },
    { time: "09:15 - 11:15", subject: "OOP(L)", teacher: "PNB", room: "A028", type: "Lab", batch: "C3" },
    { time: "09:15 - 11:15", subject: "Library Hours", type: "Activity", batch: "C1" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "AEC", teacher: "RAP", room: "A026", type: "Lecture" },
    { time: "12:30 - 01:30", subject: "GUI", teacher: "AV", room: "A026", type: "Lecture" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC(T)", teacher: "RAP", room: "A026", type: "Tutorial", batch: "C2" },
    { time: "02:15 - 03:15", subject: "Library Hours", type: "Activity", batch: "C1/C3" },
    { time: "03:15 - 04:15", subject: "TG Contact Hour", type: "Activity" },
  ],
  "Friday": [
    { time: "09:15 - 11:15", subject: "MEC(L)", teacher: "MSA", room: "A107", type: "Lab", batch: "C3" },
    { time: "09:15 - 11:15", subject: "IKS(L)", teacher: "PJK", room: "A026", type: "Lab", batch: "C1" },
    { time: "09:15 - 11:15", subject: "MEE(L)", teacher: "VS", room: "B001", type: "Lab", batch: "C2" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "GUI(L)", teacher: "AV", room: "A110", type: "Lab", batch: "C3" },
    { time: "11:30 - 01:30", subject: "OOP(L)", teacher: "PNB", room: "A028", type: "Lab", batch: "C1" },
    { time: "11:30 - 01:30", subject: "DTI(L)", teacher: "AP", room: "A026", type: "Lab", batch: "C2" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC(T)", teacher: "RAP", room: "A027", type: "Tutorial", batch: "C3" },
    { time: "02:15 - 04:15", subject: "DTI(L)", teacher: "AP", room: "A026", type: "Lab", batch: "C1" },
    { time: "02:15 - 04:15", subject: "Library Hours", type: "Activity", batch: "C2" },
    { time: "03:15 - 04:15", subject: "—", type: "Free", batch: "C3" },
  ],
  "Saturday": [
    { time: "09:15 - 10:15", subject: "CC Activity", type: "Activity" },
    { time: "10:15 - 11:15", subject: "Remedial Classes", type: "Activity" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "CC Activity", type: "Activity" },
    { time: "12:30 - 01:30", subject: "Remedial Classes", type: "Activity" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "CC Activity", type: "Activity" },
    { time: "03:15 - 04:15", subject: "Remedial Classes", type: "Activity" },
  ],
};

export const DIVISION_D_SCHEDULE: Record<string, any[]> = {
  "Monday": [
    { time: "09:15 - 11:15", subject: "GUI(L)", teacher: "AV", room: "A105", type: "Lab", batch: "D1" },
    { time: "09:15 - 11:15", subject: "OOP(L)", teacher: "PNB", room: "A028", type: "Lab", batch: "D2" },
    { time: "09:15 - 11:15", subject: "DTI(L)", teacher: "AP", room: "A212", type: "Lab", batch: "D3" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "MEC(L)", teacher: "MSA", room: "A107", type: "Lab", batch: "D1" },
    { time: "11:30 - 01:30", subject: "IKS(L)", teacher: "AV", room: "A212", type: "Lab", batch: "D2" },
    { time: "11:30 - 01:30", subject: "MEE(L)", teacher: "VS", room: "B010", type: "Lab", batch: "D3" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC(T)", teacher: "RAP", room: "A212", type: "Tutorial", batch: "D3" },
    { time: "02:15 - 03:15", subject: "Library Hours", type: "Activity", batch: "D1/D2" },
    { time: "03:15 - 04:15", subject: "AEC", teacher: "RAP", room: "A212", type: "Lecture" },
  ],
  "Tuesday": [
    { time: "09:15 - 11:15", subject: "MEC(L)", teacher: "MSA", room: "A107", type: "Lab", batch: "D2" },
    { time: "09:15 - 11:15", subject: "IKS(L)", teacher: "SNE", room: "A212", type: "Lab", batch: "D3" },
    { time: "09:15 - 11:15", subject: "MEE(L)", teacher: "VS", room: "B001", type: "Lab", batch: "D1" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "AEC", teacher: "RAP", room: "A212", type: "Lecture" },
    { time: "12:30 - 01:30", subject: "OOP", teacher: "PNB", room: "A212", type: "Lecture" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "MEC", teacher: "MSA", room: "A212", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "AEC(T)", teacher: "RAP", room: "A212", type: "Tutorial", batch: "D2" },
    { time: "03:15 - 04:15", subject: "Library Hours", type: "Activity", batch: "D3/D1" },
  ],
  "Wednesday": [
    { time: "09:15 - 11:15", subject: "GUI(L)", teacher: "AV", room: "A112", type: "Lab", batch: "D2" },
    { time: "09:15 - 11:15", subject: "OOP(L)", teacher: "PNB", room: "A028", type: "Lab", batch: "D3" },
    { time: "09:15 - 11:15", subject: "DTI(L)", teacher: "AP", room: "A212", type: "Lab", batch: "D1" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "GUI", teacher: "AV", room: "A212", type: "Lecture" },
    { time: "12:30 - 01:30", subject: "AEC", teacher: "RAP", room: "A212", type: "Lecture" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "MEE", teacher: "VS", room: "A212", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "OOP", teacher: "PNB", room: "A212", type: "Lecture" },
  ],
  "Thursday": [
    { time: "09:15 - 11:15", subject: "MEC(L)", teacher: "MSA", room: "A107", type: "Lab", batch: "D3" },
    { time: "09:15 - 11:15", subject: "IKS(L)", teacher: "SMK", room: "A212", type: "Lab", batch: "D1" },
    { time: "09:15 - 11:15", subject: "MEE(L)", teacher: "VS", room: "B001", type: "Lab", batch: "D2" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "MEE", teacher: "VS", room: "A212", type: "Lecture" },
    { time: "12:30 - 01:30", subject: "Library Hours", type: "Activity" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "MEC", teacher: "MSA", room: "A212", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "GUI", teacher: "AV", room: "A212", type: "Lecture" },
  ],
  "Friday": [
    { time: "09:15 - 11:15", subject: "GUI(L)", teacher: "AV", room: "A105", type: "Lab", batch: "D3" },
    { time: "09:15 - 11:15", subject: "OOP(L)", teacher: "PNB", room: "A028", type: "Lab", batch: "D1" },
    { time: "09:15 - 11:15", subject: "DTI(L)", teacher: "AP", room: "A212", type: "Lab", batch: "D2" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "AEC", teacher: "RAP", room: "A212", type: "Lecture" },
    { time: "12:30 - 01:30", subject: "TG Contact Hour", type: "Activity" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "MEC", teacher: "MSA", room: "A212", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "AEC(T)", teacher: "RAP", room: "A212", type: "Tutorial", batch: "D1" },
    { time: "03:15 - 04:15", subject: "Library Hours", type: "Activity", batch: "D3/D2" },
  ],
  "Saturday": [
    { time: "09:15 - 10:15", subject: "CC Activity", type: "Activity" },
    { time: "10:15 - 11:15", subject: "Remedial Classes", type: "Activity" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "CC Activity", type: "Activity" },
    { time: "12:30 - 01:30", subject: "Remedial Classes", type: "Activity" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "CC Activity", type: "Activity" },
    { time: "03:15 - 04:15", subject: "Remedial Classes", type: "Activity" },
  ],
};

export const DIVISION_E_SCHEDULE: Record<string, any[]> = {
  "Monday": [
    { time: "09:15 - 10:15", subject: "GUI", teacher: "RRJ", room: "A213", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "Library Hours", type: "Activity" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "GUI(L)", teacher: "SRS", room: "A110", type: "Lab", batch: "E1" },
    { time: "11:30 - 01:30", subject: "OOP(L)", teacher: "MBS", room: "A105", type: "Lab", batch: "E2" },
    { time: "11:30 - 01:30", subject: "DTI(L)", teacher: "YDN", room: "A024", type: "Lab", batch: "E3" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "MEE", teacher: "VS", room: "A213", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "AEC(T)", teacher: "SRS", room: "A213", type: "Tutorial", batch: "E3" },
    { time: "03:15 - 04:15", subject: "Library Hours", type: "Activity", batch: "E1/E2" },
  ],
  "Tuesday": [
    { time: "09:15 - 10:15", subject: "AEC", teacher: "SRS", room: "A213", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "AEC", teacher: "SRS", room: "A213", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "MEC(L)", teacher: "SNE", room: "A107", type: "Lab", batch: "E1" },
    { time: "11:30 - 01:30", subject: "IKS(L)", teacher: "SMK", room: "A213", type: "Lab", batch: "E2" },
    { time: "11:30 - 01:30", subject: "MEE(L)", teacher: "TBJ", room: "B001", type: "Lab", batch: "E3" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "TG Contact Hour", type: "Activity" },
    { time: "03:15 - 04:15", subject: "MEE", teacher: "VS", room: "A213", type: "Lecture" },
  ],
  "Wednesday": [
    { time: "09:15 - 10:15", subject: "MEC", teacher: "PAD", room: "A213", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "MEC", teacher: "PAD", room: "A213", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "GUI(L)", teacher: "TBJ", room: "A110", type: "Lab", batch: "E2" },
    { time: "11:30 - 01:30", subject: "OOP(L)", teacher: "RRJ", room: "A105", type: "Lab", batch: "E3" },
    { time: "11:30 - 01:30", subject: "DTI(L)", teacher: "AP", room: "A213", type: "Lab", batch: "E1" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC", teacher: "SRS", room: "A213", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "AEC(T)", teacher: "SRS", room: "A213", type: "Tutorial", batch: "E2" },
    { time: "03:15 - 04:15", subject: "Library Hours", type: "Activity", batch: "E1/E3" },
  ],
  "Thursday": [
    { time: "09:15 - 11:15", subject: "MEC(L)", teacher: "SNE", room: "A107", type: "Lab", batch: "E2" },
    { time: "09:15 - 11:15", subject: "IKS(L)", teacher: "SMK", room: "A212", type: "Lab", batch: "E3" },
    { time: "09:15 - 11:15", subject: "MEE(L)", teacher: "TBJ", room: "B001", type: "Lab", batch: "E1" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "MEC(L)", teacher: "SNE", room: "A107", type: "Lab", batch: "E3" },
    { time: "11:30 - 01:30", subject: "IKS(L)", teacher: "SMK", room: "A211", type: "Lab", batch: "E1" },
    { time: "11:30 - 01:30", subject: "MEE(L)", teacher: "TBJ", room: "B001", type: "Lab", batch: "E2" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "OOP", teacher: "PNB", room: "A213", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "AEC(T)", teacher: "SRS", room: "A213", type: "Tutorial", batch: "E1" },
    { time: "03:15 - 04:15", subject: "Library Hours", type: "Activity", batch: "E3/E2" },
  ],
  "Friday": [
    { time: "09:15 - 10:15", subject: "GUI", teacher: "RRJ", room: "A213", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "MEC", teacher: "PAD", room: "A213", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "GUI(L)", teacher: "TBJ", room: "A110", type: "Lab", batch: "E3" },
    { time: "11:30 - 01:30", subject: "OOP(L)", teacher: "RRJ", room: "A105", type: "Lab", batch: "E1" },
    { time: "11:30 - 01:30", subject: "DTI(L)", teacher: "AP", room: "A026", type: "Lab", batch: "E2" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC", teacher: "SRS", room: "A213", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "OOP", teacher: "PNB", room: "A213", type: "Lecture" },
  ],
  "Saturday": [
    { time: "09:15 - 10:15", subject: "CC Activity", type: "Activity" },
    { time: "10:15 - 11:15", subject: "Remedial Classes", type: "Activity" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "CC Activity", type: "Activity" },
    { time: "12:30 - 01:30", subject: "Remedial Classes", type: "Activity" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "CC Activity", type: "Activity" },
    { time: "03:15 - 04:15", subject: "Remedial Classes", type: "Activity" },
  ],
};

export const DIVISION_F_SCHEDULE: Record<string, any[]> = {
  "Monday": [
    { time: "09:15 - 10:15", subject: "AEC", teacher: "SSM", room: "A210", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "OOP", teacher: "PJK", room: "A210", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "AEC(T)", teacher: "SSM", room: "A210", type: "Tutorial", batch: "F1" },
    { time: "11:30 - 12:30", subject: "Library Hours", type: "Activity", batch: "F2/F3" },
    { time: "12:30 - 01:30", subject: "MEP", teacher: "PMR", room: "A210", type: "Lecture" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 04:15", subject: "MEP(L)", teacher: "PMR", room: "B003", type: "Lab", batch: "F1" },
    { time: "02:15 - 04:15", subject: "IKS(L)", teacher: "SSP", room: "A028", type: "Lab", batch: "F2" },
    { time: "02:15 - 04:15", subject: "ADE(L)", teacher: "SBM", room: "B001", type: "Lab", batch: "F3" },
  ],
  "Tuesday": [
    { time: "09:15 - 10:15", subject: "MEP", teacher: "PMR", room: "A210", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "AEC", teacher: "SSM", room: "A210", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "AEC(T)", teacher: "SSM", room: "A210", type: "Tutorial", batch: "F2" },
    { time: "11:30 - 12:30", subject: "Library Hours", type: "Activity", batch: "F1/F3" },
    { time: "12:30 - 01:30", subject: "OOP", teacher: "PJK", room: "A210", type: "Lecture" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 04:15", subject: "MR(L)", teacher: "SSP", room: "B004", type: "Lab", batch: "F2" },
    { time: "02:15 - 04:15", subject: "MPW(L)", teacher: "JSJ", room: "A006", type: "Lab", batch: "F3" },
    { time: "02:15 - 04:15", subject: "OOP(L)", teacher: "PJK", room: "A028", type: "Lab", batch: "F1" },
  ],
  "Wednesday": [
    { time: "09:15 - 10:15", subject: "MR", teacher: "SSP", room: "A210", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "MR", teacher: "SSP", room: "A210", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "AEC(T)", teacher: "SSM", room: "A210", type: "Tutorial", batch: "F3" },
    { time: "11:30 - 12:30", subject: "Library Hours", type: "Activity", batch: "F1/F2" },
    { time: "12:30 - 01:30", subject: "ADE", teacher: "SBM", room: "A210", type: "Lecture" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 04:15", subject: "MEP(L)", teacher: "PMR", room: "B003", type: "Lab", batch: "F2" },
    { time: "02:15 - 04:15", subject: "IKS(L)", teacher: "SSP", room: "A028", type: "Lab", batch: "F3" },
    { time: "02:15 - 04:15", subject: "ADE(L)", teacher: "SBM", room: "B001", type: "Lab", batch: "F1" },
  ],
  "Thursday": [
    { time: "09:15 - 10:15", subject: "AEC", teacher: "SSM", room: "A210", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "TG Contact Hour", type: "Activity" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "MR(L)", teacher: "SSP", room: "B004", type: "Lab", batch: "F1" },
    { time: "11:30 - 01:30", subject: "MPW(L)", teacher: "JSJ", room: "A006", type: "Lab", batch: "F2" },
    { time: "11:30 - 01:30", subject: "OOP(L)", teacher: "PJK", room: "A028", type: "Lab", batch: "F3" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 04:15", subject: "MR(L)", teacher: "SSP", room: "B004", type: "Lab", batch: "F3" },
    { time: "02:15 - 04:15", subject: "MPW(L)", teacher: "JSJ", room: "A006", type: "Lab", batch: "F1" },
    { time: "02:15 - 04:15", subject: "OOP(L)", teacher: "PJK", room: "A028", type: "Lab", batch: "F2" },
  ],
  "Friday": [
    { time: "09:15 - 10:15", subject: "AEC", teacher: "SSM", room: "A210", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "ADE", teacher: "SBM", room: "A210", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "Library Hours", type: "Activity" },
    { time: "12:30 - 01:30", subject: "MEP", teacher: "PMR", room: "A210", type: "Lecture" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 04:15", subject: "MEP(L)", teacher: "PMR", room: "B003", type: "Lab", batch: "F3" },
    { time: "02:15 - 04:15", subject: "IKS(L)", teacher: "SSM", room: "A210", type: "Lab", batch: "F1" },
    { time: "02:15 - 04:15", subject: "ADE(L)", teacher: "SBM", room: "B001", type: "Lab", batch: "F2" },
  ],
  "Saturday": [
    { time: "09:15 - 10:15", subject: "CC Activity", type: "Activity" },
    { time: "10:15 - 11:15", subject: "Remedial Classes", type: "Activity" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "CC Activity", type: "Activity" },
    { time: "12:30 - 01:30", subject: "Remedial Classes", type: "Activity" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "CC Activity", type: "Activity" },
    { time: "03:15 - 04:15", subject: "Remedial Classes", type: "Activity" },
  ],
};

export const DIVISION_G_SCHEDULE: Record<string, any[]> = {
  "Monday": [
    { time: "09:15 - 10:15", subject: "ADE", teacher: "SBM", room: "A211", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "MR", teacher: "YDN", room: "A211", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "MR(L)", teacher: "SMK", room: "B004", type: "Lab", batch: "G1" },
    { time: "11:30 - 01:30", subject: "MPW(L)", teacher: "SJ", room: "A005", type: "Lab", batch: "G2" },
    { time: "11:30 - 01:30", subject: "OOP(L)", teacher: "PJK", room: "A028", type: "Lab", batch: "G3" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "MR", teacher: "YDN", room: "A211", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "AEC(T)", teacher: "SSM", room: "A211", type: "Tutorial", batch: "G1" },
    { time: "03:15 - 04:15", subject: "Library Hours", type: "Activity", batch: "G2/G3" },
  ],
  "Tuesday": [
    { time: "09:15 - 10:15", subject: "OOP", teacher: "PJK", room: "A211", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "ADE", teacher: "SBM", room: "A211", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "MEP(L)", teacher: "PMR", room: "B003", type: "Lab", batch: "G1" },
    { time: "11:30 - 01:30", subject: "IKS(L)", teacher: "SSP", room: "A028", type: "Lab", batch: "G2" },
    { time: "11:30 - 01:30", subject: "ADE(L)", teacher: "SBM", room: "B001", type: "Lab", batch: "G3" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC", teacher: "SSM", room: "A211", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "AEC(T)", teacher: "SSM", room: "A211", type: "Tutorial", batch: "G2" },
    { time: "03:15 - 04:15", subject: "Library Hours", type: "Activity", batch: "G1/G3" },
  ],
  "Wednesday": [
    { time: "09:15 - 10:15", subject: "MEP", teacher: "PMR", room: "A211", type: "Lecture" },
    { time: "10:15 - 11:15", subject: "MEP", teacher: "PMR", room: "A211", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "MR(L)", teacher: "YDN", room: "B004", type: "Lab", batch: "G2" },
    { time: "11:30 - 01:30", subject: "MPW(L)", teacher: "SJ", room: "A005", type: "Lab", batch: "G3" },
    { time: "11:30 - 01:30", subject: "OOP(L)", teacher: "PJK", room: "A028", type: "Lab", batch: "G1" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC", teacher: "SSM", room: "A211", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "AEC(T)", teacher: "SSM", room: "A211", type: "Tutorial", batch: "G3" },
    { time: "03:15 - 04:15", subject: "Library Hours", type: "Activity", batch: "G1/G2" },
  ],
  "Thursday": [
    { time: "09:15 - 11:15", subject: "MEP(L)", teacher: "PMR", room: "B003", type: "Lab", batch: "G2" },
    { time: "09:15 - 11:15", subject: "IKS(L)", teacher: "SSP", room: "A028", type: "Lab", batch: "G3" },
    { time: "09:15 - 11:15", subject: "ADE(L)", teacher: "SBM", room: "B001", type: "Lab", batch: "G1" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "MEP(L)", teacher: "PMR", room: "B003", type: "Lab", batch: "G3" },
    { time: "11:30 - 01:30", subject: "IKS(L)", teacher: "SMK", room: "A211", type: "Lab", batch: "G1" },
    { time: "11:30 - 01:30", subject: "ADE(L)", teacher: "SBM", room: "B001", type: "Lab", batch: "G2" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "AEC", teacher: "SSM", room: "A211", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "AEC", teacher: "SSM", room: "A211", type: "Lecture" },
  ],
  "Friday": [
    { time: "09:15 - 10:15", subject: "TG Contact Hour", type: "Activity" },
    { time: "10:15 - 11:15", subject: "MEP", teacher: "PMR", room: "A211", type: "Lecture" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 01:30", subject: "MR(L)", teacher: "YDN", room: "B004", type: "Lab", batch: "G3" },
    { time: "11:30 - 01:30", subject: "MPW(L)", teacher: "SJ", room: "A005", type: "Lab", batch: "G1" },
    { time: "11:30 - 01:30", subject: "OOP(L)", teacher: "PJK", room: "A028", type: "Lab", batch: "G2" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "OOP", teacher: "PJK", room: "A211", type: "Lecture" },
    { time: "03:15 - 04:15", subject: "Library Hours", type: "Activity" },
  ],
  "Saturday": [
    { time: "09:15 - 10:15", subject: "CC Activity & Remedial Classes", type: "Activity" },
    { time: "10:15 - 11:15", subject: "CC Activity & Remedial Classes", type: "Activity" },
    { time: "11:15 - 11:30", subject: "Break", type: "Break" },
    { time: "11:30 - 12:30", subject: "CC Activity & Remedial Classes", type: "Activity" },
    { time: "12:30 - 01:30", subject: "CC Activity & Remedial Classes", type: "Activity" },
    { time: "01:30 - 02:15", subject: "Lunch Break", type: "Break" },
    { time: "02:15 - 03:15", subject: "CC Activity & Remedial Classes", type: "Activity" },
    { time: "03:15 - 04:15", subject: "CC Activity & Remedial Classes", type: "Activity" },
  ],
};

